# Paths
DATA_DIR: "data"
MODEL_DIR: "models"
OUTPUT_DIR: "output"

# Data Preprocessing
FEATURES:
  - "REF_ESP" # Recomendacion del Especialista
  # - "C_P" # Esto aparentemente tiene el mismo valor que el label?
  # - "EDAD"
  # - "SEXO"
  # - "AVSC1"
  # - "AVCC1" # Hay varios features como este que tienen valores similares en muchos casos
  # - "ESF1"
  # - "CIL1"
  # - "EJE1"
  # - "AVSC2"
  # - "AVCC2"
  - "REF_POST" # ESF2 + CIL2/2 # Recomendacion del Especialista
  # - "DELTA_REF" # REF_POST - REF_ESP
  # - "ESF2"
  # - "CIL2"
  # - "EJE2"
  # - "MF1"
  # - "MD1"
  - "K1" # Recomendacion del Especialista
  # - "WTW"
  # - "CENTRO"
  # - "DP"
  # - "GC"
  # - "PCA" # Recomendacion del Especialista
  - "LAXIAL" # Recomendacion del Especialista
  - "LENTE_DEF" # Este es el Label
MODELS:
  # - "432"
  # - "533"
  - "903"
  # - "933"
  # - "944"
SETS:
  - "G"
  - "E"

# Training
EPOCHS: 1024
BATCH_SIZE: 64
LEARNING_RATE: 0.0001
RANDOM_STATE: 39
VAL_SPLIT: 0.2

# Tests
NORM_ALPHA: 0.05
ALPHA: 0.05
