# Paths
DATA_DIR: "data"
MODEL_DIR: "models"
OUTPUT_DIR: "output"

# Data Preprocessing
FEATURES:
  - "REF_ESP" # ORIG
  # - "C_P" # Esto aparentemente tiene el mismo valor que el label?
  - "EDAD"
  # - "SEXO"
  - "AVSC1"
  - "AVCC1" # Hay varios features como este que tienen valores similares en muchos casos
  - "ESF1"
  - "CIL1"
  - "EJE1"
  - "AVSC2"
  - "AVCC2"
  - "ESF2+CIL2/2" # ORIG
  # - "ESF2"
  # - "CIL2"
  - "EJE2"
  - "MF1"
  - "MD1"
  - "K1" # ORIG
  # - "WTW"
  - "CENTRO"
  # - "DP"
  - "GC"
  - "PCA" # ORIG
  - "LAXIAL" # ORIG
  - "LENTE_DEF" # Este es el Label # ORIG
MODELS:
  - "432"
  # - "533"
  # - "903"
  # - "933"
  # - "944"
SETS:
  - "G"
  # - "M"
  # - "F"
FOLDS: 10

# Training
EPOCHS: 1000
BATCH_SIZE: 500
LEARNING_RATE: 0.001
